"""
Django urls for invetoryVerbalInformation project.

Generated by 'juan-diego'
date_create: 21/03/20223

This url file is a set of patterns tha Django will use to compare against the incoming URL to find the correct answer
In the case of this project, we create urls for each views.
"""
from django.urls import path
from verbal_information.views import VerbalInformationCreateViewSet
from verbal_information.views import VerbalInformationRetrieveUpdateDeleteViewSet
from verbal_information.views import VerbalInformationListViewSet
from verbal_information.views import RequestTestAPI
from .docs import schema_view

urlpatterns = [
    path(
        "api/v1/Verbal/Informations/create",
        VerbalInformationCreateViewSet.as_view(),
        name="VirtualInformation_create",
    ),
    path(
        "api/v1/Verbal/Informations/<int:pk>/retrieve",
        VerbalInformationRetrieveUpdateDeleteViewSet.as_view(),
        name="VerbalInformation_retrieve",
    ),
    path(
        "api/v1/Verbal/Informations/<int:pk>/update",
        VerbalInformationRetrieveUpdateDeleteViewSet.as_view(),
        name="VerbalInformation_update",
    ),
    path(
        "api/v1/Verbal/Informations/<int:pk>/destroy",
        VerbalInformationRetrieveUpdateDeleteViewSet.as_view(),
        name="VerbalInformation_destroy",
    ),
    path(
        "api/v1/Verbal/Informations/list",
        VerbalInformationListViewSet.as_view(),
        name="VerbalInformation_list",
    ),
    path("api/v1/request/", RequestTestAPI.as_view(), name="VerbalInformation_test"),
    path(
        "docs/",
        schema_view.with_ui("swagger", cache_timeout=None),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/", schema_view.with_ui("redoc", cache_timeout=None), name="schema-redoc"
    ),
]
