"""
Django models for VerbalInformation app

Generated by 'juan-diego'
date-create: 21/03/2023

This model has a function the creating a brand.
"""

from django.db import models


class VerbalInformation(models.Model):
    """
    Models:
        "id": Identification number, generated automatically.
        "company_id": comapny identification number.
        "cod_assignments": Attribution Code.
        "cod_usefulness": Service Code.
        "cod_request_date": Request Date.
        "cod_delivery_date": Delivery date.
        "cod_requester": Requester.
        "cod_rg": RG code.
        "cod_cpf": CPF code.
        "cod_delivery_name": Deliveryman Name.
        "cod_delivery_rg": Delivery person RG.
        "cod_delivery_cpf": Delivery person CPF.
        "cod_subject": Subject.


    """

    id = models.AutoField(primary_key=True)
    company_id = models.IntegerField(
        blank=False, null=False, verbose_name="ID da compania", db_column="company_id"
    )
    cod_assignments = models.IntegerField(
        null=False,
        blank=False,
        verbose_name="Código de Atribuição",
        db_column="cod_assignments",
    )
    cod_usefulness = models.IntegerField(
        null=False,
        blank=False,
        verbose_name="Código da Serventia",
        db_column="cod_usefulness",
    )
    cod_request_date = models.DateField(
        null=True,
        blank=True,
        verbose_name="Data do Pedido",
        db_column="cod_request_date",
    )
    cod_delivery_date = models.DateField(
        null=True,
        blank=True,
        verbose_name="Data de Entrega",
        db_column="cod_delivery_date",
    )
    cod_requester = models.CharField(
        max_length=60,
        null=True,
        blank=True,
        verbose_name="Solicitante",
        db_column="cod_requester",
    )
    cod_rg = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name="Código do RG",
        db_column="cod_rg",
    )
    cod_cpf = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name="Código do CPF",
        db_column="cod_cpf",
    )
    cod_delivery_name = models.CharField(
        max_length=60,
        null=True,
        blank=True,
        verbose_name="Nome do Entregador",
        db_column="cod_delivery_name",
    )
    cod_delivery_rg = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name="RG do entregador",
        db_column="cod_delivery_rg",
    )
    cod_delivery_cpf = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name="CPF do entregador",
        db_column="cod_delivery_cpf",
    )
    cod_subject = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        verbose_name="Assunto",
        db_column="cod_subject",
    )

    class Meta:
        """Defining the class name with the database"""

        db_table = "verbal_informations"
