"""
Django Serializers for brand app.

Generated by 'juan-diego'
date_create: 21/03/2023

this serializer file has the function of converting complex data ( in our case the rest_framework and the models )
into native python data types that can be easily rendered in JSON, XML or other types of content.
"""


from rest_framework import serializers
from verbal_information.models import VerbalInformation


class VerbalInformationSerializers(serializers.ModelSerializer):
    """
    A 'Serializer' of 'VerbalInformation', With Function:
    * Serializer Data: Transform Object to Data.
    * Deserializer Data: Transform Data to Object
    """

    class Meta:
        model = VerbalInformation
        fields = "__all__"
