CREATE TABLE verbal_informations (
    id INT NOT NULL AUTO_INCREMENT,
    company_id INT NOT NULL,  
    cod_assignments INT NOT NULL,   
    cod_usefulness INT NOT NULL,
    cod_request_date DATE,
    cod_delivery_date DATE,
    cod_requester VARCHAR(60),
    cod_rg VARCHAR(20),
    cod_cpf VARCHAR(20),
    cod_delivery_name VARCHAR (60),
    cod_delivery_rg VARCHAR (20),
    cod_delivery_cpf VARCHAR (20),
    cod_subject VARCHAR (200),
    CONSTRAINT pk_verbal_informations primary key (id),
);
