CREATE TABLE verbal_informations (
    id INT NOT NULL AUTO_INCREMENT,
    company_id INT NOT NULL,  
    assignments INT NOT NULL,   
    usefulness INT NOT NULL,
    request_date DATE,
    delivery_date DATE,
    requester VARCHAR(60),
    rg VARCHAR(20),
    cpf VARCHAR(20),
    delivery_name VARCHAR (60),
    delivery_rg VARCHAR (20),
    delivery_cpf VARCHAR (20),
    cod_subject VARCHAR (200),
    CONSTRAINT pk_verbal_informations primary key (id),
);
